title: Build end-to-end CI/CD capabilities directly in GitHub
description: With GitHub Actions, you can create and set up workflows in your repository to build, test, and deploy your code.
steps:
  - link: 'https://www.youtube.com/watch?v=s-WkdSXRDA4'
    video: 'https://www.youtube.com/embed/s-WkdSXRDA4'
    title: Webinar Introduction to GitHub Actions
    description: >-
      Learn how GitHub Actions enable you to automate your software development
      cycle and deploy applications to Azure. Weâ€™ll walk you through how to
      create a basic GitHub workflow.
